services:
  - type: web
    name: disease-classification
    runtime: python
    buildCommand: pip install -r web_app/requirements.txt
    startCommand: gunicorn --chdir web_app app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
